FROM alpine:3.16@sha256:686d8c9dfa6f3ccfc8230bc3178d23f84eeaf7e457f36f271ab1acc53015037c

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-admin"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-admin"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-admin"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-admin"

ADD dist/drone-admin /bin/
ENTRYPOINT [ "/bin/drone-admin" ]
