FROM arm32v7/alpine:3.16@sha256:0dc112f0cf79af2654a164af9223723348b07ce2b798bbcb858984fb64d8e13b

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-admin"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-admin"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-admin"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-admin"

ADD dist/drone-admin /bin/
ENTRYPOINT [ "/bin/drone-admin" ]
