FROM alpine:3.16@sha256:b95359c2505145f16c6aa384f9cc74eeff78eb36d308ca4fd902eeeb0a0b161b

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="drone-admin"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/drone-admin"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/drone-admin"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/drone-admin"

ADD dist/drone-admin /bin/
ENTRYPOINT [ "/bin/drone-admin" ]
